services:
  postgres:
    image: postgres:16.9
    container_name: sample-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=order_platform
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - order-network


  redis:
    image: redis:7.0.15
    container_name: sample-redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    networks:
      - order-network

  mongodb:
    image: mongo:8.0.12
    container_name: store-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - ./.env
    networks:
      - order-network
networks:
  order-network:
    driver: bridge